algoritmo "semnome"
// Função :
// Autor :
// Data : 27/02/2019
// Seção de Declarações 
var

   //faça um programa que leia ano meses e dias e apresente somente os dias


idade, dias, mes : inteiro
inicio

escreva("Qual a idade: ")
leia(idade)

escreva("Quantos meses: ")
leia(mes)

escreva("Quantos dias: ")
leia(dias)

dias <- dias + (idade * 365) + (mes * 30)

escreva("Você possui ", dias, " dias de vida")


// Seção de Comandos 
fimalgoritmo
